version: '3.8'

services:
  gitgen:
    build: .
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
    volumes:
      - gitgen-temp:/app/temp
      - gitgen-uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3030/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  gitgen-dev:
    build: .
    ports:
      - "3002:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
    volumes:
      - ./src:/app/src
      - ./client/src:/app/client/src
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
      - ./client/package.json:/app/client/package.json
    command: npm run dev
    profiles:
      - dev

volumes:
  gitgen-temp:
  gitgen-uploads: