version: '3.8'

services:
  gitgen:
    build: .
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
    volumes:
      - ./temp:/app/temp
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3030/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  gitgen-dev:
    build: .
    ports:
      - "3002:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    command: npm run dev
    profiles:
      - dev